// Package generated by tuplegen, DO NOT EDIT!

package tuple

type Tuple1[A any] struct {
	A A
}

func NewTuple1[A any](a A) Tuple1[A] {
	return Tuple1[A]{
		A: a,
	}
}

type Tuple2[A, B any] struct {
	A A
	B B
}

func NewTuple2[A, B any](a A, b B) Tuple2[A, B] {
	return Tuple2[A, B]{
		A: a,
		B: b,
	}
}

type Tuple3[A, B, C any] struct {
	A A
	B B
	C C
}

func NewTuple3[A, B, C any](a A, b B, c C) Tuple3[A, B, C] {
	return Tuple3[A, B, C]{
		A: a,
		B: b,
		C: c,
	}
}

type Tuple4[A, B, C, D any] struct {
	A A
	B B
	C C
	D D
}

func NewTuple4[A, B, C, D any](a A, b B, c C, d D) Tuple4[A, B, C, D] {
	return Tuple4[A, B, C, D]{
		A: a,
		B: b,
		C: c,
		D: d,
	}
}

type Tuple5[A, B, C, D, E any] struct {
	A A
	B B
	C C
	D D
	E E
}

func NewTuple5[A, B, C, D, E any](a A, b B, c C, d D, e E) Tuple5[A, B, C, D, E] {
	return Tuple5[A, B, C, D, E]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
	}
}

type Tuple6[A, B, C, D, E, F any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
}

func NewTuple6[A, B, C, D, E, F any](a A, b B, c C, d D, e E, f F) Tuple6[A, B, C, D, E, F] {
	return Tuple6[A, B, C, D, E, F]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
	}
}

type Tuple7[A, B, C, D, E, F, G any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
}

func NewTuple7[A, B, C, D, E, F, G any](a A, b B, c C, d D, e E, f F, g G) Tuple7[A, B, C, D, E, F, G] {
	return Tuple7[A, B, C, D, E, F, G]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
		G: g,
	}
}

type Tuple8[A, B, C, D, E, F, G, H any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
}

func NewTuple8[A, B, C, D, E, F, G, H any](a A, b B, c C, d D, e E, f F, g G, h H) Tuple8[A, B, C, D, E, F, G, H] {
	return Tuple8[A, B, C, D, E, F, G, H]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
		G: g,
		H: h,
	}
}

type Tuple9[A, B, C, D, E, F, G, H, I any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
}

func NewTuple9[A, B, C, D, E, F, G, H, I any](a A, b B, c C, d D, e E, f F, g G, h H, i I) Tuple9[A, B, C, D, E, F, G, H, I] {
	return Tuple9[A, B, C, D, E, F, G, H, I]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
		G: g,
		H: h,
		I: i,
	}
}

type Tuple10[A, B, C, D, E, F, G, H, I, J any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
}

func NewTuple10[A, B, C, D, E, F, G, H, I, J any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J) Tuple10[A, B, C, D, E, F, G, H, I, J] {
	return Tuple10[A, B, C, D, E, F, G, H, I, J]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
		G: g,
		H: h,
		I: i,
		J: j,
	}
}

type Tuple11[A, B, C, D, E, F, G, H, I, J, K any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
}

func NewTuple11[A, B, C, D, E, F, G, H, I, J, K any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K) Tuple11[A, B, C, D, E, F, G, H, I, J, K] {
	return Tuple11[A, B, C, D, E, F, G, H, I, J, K]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
		G: g,
		H: h,
		I: i,
		J: j,
		K: k,
	}
}

type Tuple12[A, B, C, D, E, F, G, H, I, J, K, L any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
}

func NewTuple12[A, B, C, D, E, F, G, H, I, J, K, L any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L) Tuple12[A, B, C, D, E, F, G, H, I, J, K, L] {
	return Tuple12[A, B, C, D, E, F, G, H, I, J, K, L]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
		G: g,
		H: h,
		I: i,
		J: j,
		K: k,
		L: l,
	}
}

type Tuple13[A, B, C, D, E, F, G, H, I, J, K, L, M any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
	M M
}

func NewTuple13[A, B, C, D, E, F, G, H, I, J, K, L, M any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L, m M) Tuple13[A, B, C, D, E, F, G, H, I, J, K, L, M] {
	return Tuple13[A, B, C, D, E, F, G, H, I, J, K, L, M]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
		G: g,
		H: h,
		I: i,
		J: j,
		K: k,
		L: l,
		M: m,
	}
}

type Tuple14[A, B, C, D, E, F, G, H, I, J, K, L, M, N any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
	M M
	N N
}

func NewTuple14[A, B, C, D, E, F, G, H, I, J, K, L, M, N any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L, m M, n N) Tuple14[A, B, C, D, E, F, G, H, I, J, K, L, M, N] {
	return Tuple14[A, B, C, D, E, F, G, H, I, J, K, L, M, N]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
		G: g,
		H: h,
		I: i,
		J: j,
		K: k,
		L: l,
		M: m,
		N: n,
	}
}

type Tuple15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
	M M
	N N
	O O
}

func NewTuple15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L, m M, n N, o O) Tuple15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O] {
	return Tuple15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
		G: g,
		H: h,
		I: i,
		J: j,
		K: k,
		L: l,
		M: m,
		N: n,
		O: o,
	}
}

type Tuple16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
	M M
	N N
	O O
	P P
}

func NewTuple16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L, m M, n N, o O, p P) Tuple16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P] {
	return Tuple16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
		G: g,
		H: h,
		I: i,
		J: j,
		K: k,
		L: l,
		M: m,
		N: n,
		O: o,
		P: p,
	}
}

type Tuple17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
	M M
	N N
	O O
	P P
	Q Q
}

func NewTuple17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L, m M, n N, o O, p P, q Q) Tuple17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q] {
	return Tuple17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
		G: g,
		H: h,
		I: i,
		J: j,
		K: k,
		L: l,
		M: m,
		N: n,
		O: o,
		P: p,
		Q: q,
	}
}

type Tuple18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
	M M
	N N
	O O
	P P
	Q Q
	R R
}

func NewTuple18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L, m M, n N, o O, p P, q Q, r R) Tuple18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R] {
	return Tuple18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
		G: g,
		H: h,
		I: i,
		J: j,
		K: k,
		L: l,
		M: m,
		N: n,
		O: o,
		P: p,
		Q: q,
		R: r,
	}
}

type Tuple19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
	M M
	N N
	O O
	P P
	Q Q
	R R
	S S
}

func NewTuple19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L, m M, n N, o O, p P, q Q, r R, s S) Tuple19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S] {
	return Tuple19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
		G: g,
		H: h,
		I: i,
		J: j,
		K: k,
		L: l,
		M: m,
		N: n,
		O: o,
		P: p,
		Q: q,
		R: r,
		S: s,
	}
}

type Tuple20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
	M M
	N N
	O O
	P P
	Q Q
	R R
	S S
	T T
}

func NewTuple20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L, m M, n N, o O, p P, q Q, r R, s S, t T) Tuple20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T] {
	return Tuple20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
		G: g,
		H: h,
		I: i,
		J: j,
		K: k,
		L: l,
		M: m,
		N: n,
		O: o,
		P: p,
		Q: q,
		R: r,
		S: s,
		T: t,
	}
}

type Tuple21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
	M M
	N N
	O O
	P P
	Q Q
	R R
	S S
	T T
	U U
}

func NewTuple21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L, m M, n N, o O, p P, q Q, r R, s S, t T, u U) Tuple21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U] {
	return Tuple21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
		G: g,
		H: h,
		I: i,
		J: j,
		K: k,
		L: l,
		M: m,
		N: n,
		O: o,
		P: p,
		Q: q,
		R: r,
		S: s,
		T: t,
		U: u,
	}
}

type Tuple22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
	M M
	N N
	O O
	P P
	Q Q
	R R
	S S
	T T
	U U
	V V
}

func NewTuple22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L, m M, n N, o O, p P, q Q, r R, s S, t T, u U, v V) Tuple22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V] {
	return Tuple22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
		G: g,
		H: h,
		I: i,
		J: j,
		K: k,
		L: l,
		M: m,
		N: n,
		O: o,
		P: p,
		Q: q,
		R: r,
		S: s,
		T: t,
		U: u,
		V: v,
	}
}

type Tuple23[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
	M M
	N N
	O O
	P P
	Q Q
	R R
	S S
	T T
	U U
	V V
	W W
}

func NewTuple23[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L, m M, n N, o O, p P, q Q, r R, s S, t T, u U, v V, w W) Tuple23[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W] {
	return Tuple23[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
		G: g,
		H: h,
		I: i,
		J: j,
		K: k,
		L: l,
		M: m,
		N: n,
		O: o,
		P: p,
		Q: q,
		R: r,
		S: s,
		T: t,
		U: u,
		V: v,
		W: w,
	}
}

type Tuple24[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
	M M
	N N
	O O
	P P
	Q Q
	R R
	S S
	T T
	U U
	V V
	W W
	X X
}

func NewTuple24[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L, m M, n N, o O, p P, q Q, r R, s S, t T, u U, v V, w W, x X) Tuple24[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X] {
	return Tuple24[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
		G: g,
		H: h,
		I: i,
		J: j,
		K: k,
		L: l,
		M: m,
		N: n,
		O: o,
		P: p,
		Q: q,
		R: r,
		S: s,
		T: t,
		U: u,
		V: v,
		W: w,
		X: x,
	}
}

type Tuple25[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
	M M
	N N
	O O
	P P
	Q Q
	R R
	S S
	T T
	U U
	V V
	W W
	X X
	Y Y
}

func NewTuple25[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L, m M, n N, o O, p P, q Q, r R, s S, t T, u U, v V, w W, x X, y Y) Tuple25[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y] {
	return Tuple25[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
		G: g,
		H: h,
		I: i,
		J: j,
		K: k,
		L: l,
		M: m,
		N: n,
		O: o,
		P: p,
		Q: q,
		R: r,
		S: s,
		T: t,
		U: u,
		V: v,
		W: w,
		X: x,
		Y: y,
	}
}

type Tuple26[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z any] struct {
	A A
	B B
	C C
	D D
	E E
	F F
	G G
	H H
	I I
	J J
	K K
	L L
	M M
	N N
	O O
	P P
	Q Q
	R R
	S S
	T T
	U U
	V V
	W W
	X X
	Y Y
	Z Z
}

func NewTuple26[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z any](a A, b B, c C, d D, e E, f F, g G, h H, i I, j J, k K, l L, m M, n N, o O, p P, q Q, r R, s S, t T, u U, v V, w W, x X, y Y, z Z) Tuple26[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z] {
	return Tuple26[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z]{
		A: a,
		B: b,
		C: c,
		D: d,
		E: e,
		F: f,
		G: g,
		H: h,
		I: i,
		J: j,
		K: k,
		L: l,
		M: m,
		N: n,
		O: o,
		P: p,
		Q: q,
		R: r,
		S: s,
		T: t,
		U: u,
		V: v,
		W: w,
		X: x,
		Y: y,
		Z: z,
	}
}
